### ISSUE TITLE
Transfer to @jmccann

### ISSUE THREAD

**Issue by justincampbell** [jmccann/chef-drone#36]
Continued from #35

**Comment by justincampbell** [comment]
@jmccann You'll need to delete your fork first

**Comment by jmccann** [comment]
@justincampbell Deleted my fork.  Thanks!

**Comment by justincampbell** [comment]
Requested!

**Comment by jmccann** [comment]
@justincampbell Thanks!  Transfer is completed.  If you could add me as a collaborator or transfer ownership for https://supermarket.chef.io/cookbooks/drone that would be great!

**Comment by justincampbell** [comment]
Done!
