### ISSUE TITLE
Remove dependency on unused cookbooks

### ISSUE THREAD

**Issue by szymonpk** [jmccann/chef-drone#41]
I think, chef-vault, nginx and ssl_certificate [can be safely removed](https://github.com/jmccann/chef-drone/blob/master/metadata.rb). What do you think @jmccann?

**Comment by jmccann** [comment]
@szymonpk 👍 !!!  Thanks for pointing that out.  I'll take care of it today and do a `4.0.1` release!

**Comment by jmccann** [comment]
Done!
